name = "poe-regex-bot"
main = "src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/10 * * * *"]

[vars]
KEEPWARM_URL = "https://poe-ocr-doc-bot.onrender.com/health"
